### ISSUE TITLE
Incomplete repository. No dependencies mentioned or included

### ISSUE THREAD

**Issue by themightywolfie** [islamshahil/Text-To-SQL-Using-GPT-3#2]
You didn't include any other dependency or additional files required to run this program and everyone who tries to run it will face numerous errors. You also didn't include any instructions on how to obtain the API Key from Open AI and to put it in a json file. 

You need to add the gpt.py file which contains the classes GPT and Example and you need to mention `json` and `openai` packages as dependencies. Also add the json file in which the API Key is stored.

**Comment by islamshahil** [comment]
This is a incomplete project, when I was working, Open Ai wasn't providing any api keys. Feel free to complete the project and also create a request, I'll merge it.
